### ISSUE TITLE
train_image_size

### ISSUE THREAD

**Issue by tian0810** [cyvius96/few-shot-meta-baseline#24]
Great work! The image size of the mini dataset  in your code is setted 3*80*80, so accuracy in your paper is 3*80*80? Why don't you   use 3*84*84? Expect your help!

**Comment by cyvius96** [comment]
Thanks for your interest in our work.

This is a good point. We use the input size of 80x80 because some of recent works use 80x80 (e.g. [LEO](https://arxiv.org/pdf/1807.05960.pdf) and we wish to have a strict fair comparison to them.
Using the input size of 84x84 (as many of other recent works did) has similar results. Actually it should be slight better than 80x80 if I remember correctly.

**Comment by cyvius96** [comment]
Thanks for your interest in our work.

This is a good point. We use the input size of 80x80 because some of recent works use 80x80 (e.g. [LEO](https://arxiv.org/pdf/1807.05960.pdf)) and we wish to have a strict fair comparison to them.
Using the input size of 84x84 (as many of other recent works did) has similar results. Actually it should be slight better than 80x80 if I remember correctly.

**Comment by cyvius96** [comment]
Thanks for your interest in our work.

This is a good point. We use the input size of 80x80 because some of recent works use 80x80 (e.g. LEO) and we wish to have a strict fair comparison to them.
Using the input size of 84x84 (as many of other recent works did) has similar results. Actually it should be slightly better than 80x80 if I remember correctly.

**Comment by cyvius96** [comment]
Thanks for your interest in our work.

This is a good point. We use the input size of 80x80 because some of recent works use 80x80 (e.g. [LEO](https://arxiv.org/pdf/1807.05960.pdf)) and we wish to have a strict fair comparison to them.
Using the input size of 84x84 (as many of other recent works did) has similar results. Actually it should be slightly better than using 80x80 if I remember correctly.
